import SideElement from "@/components/blog/SideBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="min-h-screen pt-8 px-2 md:gap-16  flex flex-col md:flex-row  justify-center">
      
      {children}
      <SideElement />
   
    </main>
  );
}

